# Generated by Django 2.2.7 on 2019-11-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='counter',
        ),
    ]
