# Generated by Django 4.0.1 on 2022-04-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(null=True, to='infrastructure.Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(null=True, to='infrastructure.Tag'),
        ),
    ]
