# Generated by Django 2.1.2 on 2019-10-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=models.ManyToManyField(to='infrastructure.Tag'),
        ),
    ]
