# Generated by Django 2.2.7 on 2019-11-17 21:19

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_remove_profile_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='/images/default2.png', upload_to='images/'),
        ),
    ]
