# Generated by Django 3.1.7 on 2021-04-01 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_auto_20210401_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publisher_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_comment', to='infrastructure.organization'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publisher_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_post', to='infrastructure.organization'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publisher_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
