# Generated by Django 3.1.7 on 2021-04-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_post_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='voters',
        ),
    ]
