# Generated by Django 3.1.7 on 2021-04-04 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_post_voters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='voters',
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_of_voters', to='infrastructure.post')),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_of_voted_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
